name: Check package install
on:
  push:
    branches: [ "main" ]

jobs:
  test-package-installation:
    runs-on: ubuntu-latest
    container: maurorigo/fftwimg:first

    steps:
      - uses: actions/checkout@v4
      - name: Try to install package (for now define FFTW_INC and FFTW_LIB)
        run: |
          export FFTW_INC=/usr/local/include
          export FFTW_LIB=/usr/local/lib
          pip install .
