name: Check package install
on:
  push:
    branches: [ "main" ]

jobs:
  test-fftwimg:
    runs-on: ubuntu-latest
    container: maurorigo/fftwimg:first

    steps:
      - uses: actions/checkout@v4
      - name: Just testing new image
        run: |
          pwd
          python3 --version
