name: Check package installation
on:
  push:
    branches: [ "main" ]

jobs:
  test-package-installation:
    runs-on: ubuntu-latest
    container: maurorigo/fftwimg:latest

    steps:
      - uses: actions/checkout@v4

      - name: Try to install package and run test
        run: |
          python3 -m venv JERALDvenv
          . JERALDvenv/bin/activate
          pip install .
          export LD_LIBRARY_PATH=/usr/local/lib
          python3 losstest.py
